import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const NotoSansKr = Noto_Sans_KR({
    weight: ['100', '300', '400', '500', '700', '900'],
    display: 'swap',
    fallback: [
        // 디자이너분과 상의한 폴백 폰트
        '-apple-system',
        'Malgun Gothic',
        'Apple SD Gothic Neo',
        'Roboto',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'sans-serif',
    ],
    // preload(글꼴 파일의 크기를 줄이는 등 성능 향상)
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={NotoSansKr.className}>{children}</body>
        </html>
    );
}
